In [13]:
from credit_risk.data.readers import read_performance,read_origination
from credit_risk.target.delinquency import (
    build_24m_serious_delinquency_target,
    build_cohort_eligibility,
    build_outcome_observability
)

In [7]:
perf = read_performance("data/01_raw/freddie_mac/2015/sample_perf_2015.txt")

In [8]:
from credit_risk.target.delinquency import (
    build_24m_serious_delinquency_target,
)

target = build_24m_serious_delinquency_target(perf)

print("Final cohort:", len(target))

print(target["ever_90dpd_24m"].value_counts().sort_index())

print(target["ever_90dpd_24m"].value_counts(normalize=True).sort_index())

Final cohort: 47255
ever_90dpd_24m
0    46912
1      343
Name: count, dtype: int64
ever_90dpd_24m
0    0.992742
1    0.007258
Name: proportion, dtype: float64

In [10]:
eligibility = build_cohort_eligibility(perf)
observability = build_outcome_observability(perf)

qc = eligibility.merge(
    observability,
    on="loan_id",
    how="left",
    validate="one_to_one",
)

excluded_after_start = qc.loc[
    qc["is_start_eligible"] & ~qc["is_outcome_observable"].fillna(False)
]

print("Start eligible:", qc["is_start_eligible"].sum())
print("Unobservable after start eligibility:", len(excluded_after_start))

excluded_after_start[
        [
            "loan_id",
            "first_loan_age",
            "last_loan_age",
            "ever_serious_delinquency",
            "final_zero_balance_code",
        ]
    ]

Start eligible: 47281
Unobservable after start eligibility: 26

,loan_id,first_loan_age,last_loan_age,ever_serious_delinquency,final_zero_balance_code
84,F15Q10002812,0,11.0,False,96
1625,F15Q10047986,1,8.0,False,96
3412,F15Q10102794,0,7.0,False,96
4608,F15Q10138012,0,7.0,False,96
4729,F15Q10141205,0,8.0,False,96
5756,F15Q10171273,0,4.0,False,96
10841,F15Q10319507,1,9.0,False,96
13940,F15Q20048207,0,4.0,False,96
15510,F15Q20098908,0,5.0,False,96
20729,F15Q20269413,1,8.0,False,96
20770,F15Q20270783,0,0.0,False,96
21158,F15Q20284375,0,7.0,False,96
21298,F15Q20289225,0,21.0,False,96
22280,F15Q20322861,0,5.0,False,96
22964,F15Q20347460,0,5.0,False,96
23638,F15Q20371913,0,15.0,False,96
25051,F15Q30001341,0,11.0,False,96
26422,F15Q30042435,0,6.0,False,96
26788,F15Q30052791,0,4.0,False,96
28675,F15Q30109580,0,5.0,False,96
30207,F15Q30155311,0,17.0,False,96
30566,F15Q30167040,0,5.0,False,96
33890,F15Q30261557,0,9.0,False,96
35436,F15Q30305991,0,5.0,False,96
39425,F15Q40051817,0,7.0,False,96
41773,F15Q40113762,0,7.0,False,96

In [16]:
orig = read_origination("data/01_raw/freddie_mac/2015/sample_orig_2015.txt")
print(orig.shape)
model_base = orig.merge(
    target,
    on="loan_id",
    how="inner",
    validate="one_to_one",
)

print(model_base.shape)

(50000, 31)
(47255, 32)

In [19]:
borrower_features = [
    "credit_score",
    "vantage_score_4",
    "original_dti",
    "number_of_borrowers",
    "first_time_homebuyer_flag",
]

for col in borrower_features:
    print(f"\n{'=' * 60}")
    print(col)
    print("=" * 60)

    print("dtype:", model_base[col].dtype)
    print("missing:", model_base[col].isna().sum())
    print("unique:", model_base[col].nunique(dropna=False))

    print("\nMost common values:")
    print(model_base[col].value_counts(dropna=False).head(15))

============================================================
credit_score
============================================================
dtype: int64
missing: 0
unique: 317

Most common values:
credit_score
801    615
787    551
790    547
797    533
791    532
796    526
802    506
776    488
809    487
800    485
798    478
799    467
788    465
778    464
793    461
Name: count, dtype: int64

============================================================
vantage_score_4
============================================================
dtype: int64
missing: 0
unique: 1

Most common values:
vantage_score_4
9999    47255
Name: count, dtype: int64

============================================================
original_dti
============================================================
dtype: int64
missing: 0
unique: 51

Most common values:
original_dti
999    3899
44     2030
43     1883
45     1806
41     1794
42     1773
39     1694
40     1693
38     1615
36     1583
37     1558
33     1484
34     1470
31     1411
32     1410
Name: count, dtype: int64

============================================================
number_of_borrowers
============================================================
dtype: int64
missing: 0
unique: 2

Most common values:
number_of_borrowers
2    24078
1    23177
Name: count, dtype: int64

============================================================
first_time_homebuyer_flag
============================================================
dtype: str
missing: 0
unique: 3

Most common values:
first_time_homebuyer_flag
N    39954
Y     7300
9        1
Name: count, dtype: int64

In [21]:
for col in [
    "credit_score",
    "original_dti",
    "number_of_borrowers",
]:
    print(f"\n{'=' * 60}")
    print(col)
    print("=" * 60)

    print(model_base[col].describe())

    print("\nLowest values:")
    print(model_base[col].value_counts().sort_index().head(15))

    print("\nHighest values:")
    print(model_base[col].value_counts().sort_index().tail(15))

============================================================
credit_score
============================================================
count    47255.000000
mean       749.152661
std         47.731212
min        462.000000
25%        717.000000
50%        759.000000
75%        788.000000
max        832.000000
Name: credit_score, dtype: float64

Lowest values:
credit_score
462    1
476    1
479    1
482    1
483    1
485    1
486    1
494    2
497    1
500    1
501    1
505    1
507    1
509    1
512    2
Name: count, dtype: int64

Highest values:
credit_score
816    216
817    134
818     52
819     90
820     81
821     10
822     15
823     63
824      3
825      7
826      3
827      2
829      5
831      1
832      2
Name: count, dtype: int64

============================================================
original_dti
============================================================
count    47255.000000
mean       113.518273
std        265.696033
min          1.000000
25%         28.000000
50%         36.000000
75%         43.000000
max        999.000000
Name: original_dti, dtype: float64

Lowest values:
original_dti
1       2
2       6
3       7
4       5
5      19
6      15
7      45
8      45
9      60
10     88
11    111
12    177
13    198
14    279
15    370
Name: count, dtype: int64

Highest values:
original_dti
37     1558
38     1615
39     1694
40     1693
41     1794
42     1773
43     1883
44     2030
45     1806
46      753
47      693
48      775
49      653
50      655
999    3899
Name: count, dtype: int64

============================================================
number_of_borrowers
============================================================
count    47255.000000
mean         1.509533
std          0.499914
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: number_of_borrowers, dtype: float64

Lowest values:
number_of_borrowers
1    23177
2    24078
Name: count, dtype: int64

Highest values:
number_of_borrowers
1    23177
2    24078
Name: count, dtype: int64

In [22]:
for col in [
    "credit_score",
    "original_dti",
    "number_of_borrowers",
]:
    print(f"\n{'=' * 60}")
    print(col)
    print("=" * 60)

    print(model_base[col].describe())

    print("\nLowest values:")
    print(model_base[col].value_counts().sort_index().head(15))

    print("\nHighest values:")
    print(model_base[col].value_counts().sort_index().tail(15))

============================================================
credit_score
============================================================
count    47255.000000
mean       749.152661
std         47.731212
min        462.000000
25%        717.000000
50%        759.000000
75%        788.000000
max        832.000000
Name: credit_score, dtype: float64

Lowest values:
credit_score
462    1
476    1
479    1
482    1
483    1
485    1
486    1
494    2
497    1
500    1
501    1
505    1
507    1
509    1
512    2
Name: count, dtype: int64

Highest values:
credit_score
816    216
817    134
818     52
819     90
820     81
821     10
822     15
823     63
824      3
825      7
826      3
827      2
829      5
831      1
832      2
Name: count, dtype: int64

============================================================
original_dti
============================================================
count    47255.000000
mean       113.518273
std        265.696033
min          1.000000
25%         28.000000
50%         36.000000
75%         43.000000
max        999.000000
Name: original_dti, dtype: float64

Lowest values:
original_dti
1       2
2       6
3       7
4       5
5      19
6      15
7      45
8      45
9      60
10     88
11    111
12    177
13    198
14    279
15    370
Name: count, dtype: int64

Highest values:
original_dti
37     1558
38     1615
39     1694
40     1693
41     1794
42     1773
43     1883
44     2030
45     1806
46      753
47      693
48      775
49      653
50      655
999    3899
Name: count, dtype: int64

============================================================
number_of_borrowers
============================================================
count    47255.000000
mean         1.509533
std          0.499914
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: number_of_borrowers, dtype: float64

Lowest values:
number_of_borrowers
1    23177
2    24078
Name: count, dtype: int64

Highest values:
number_of_borrowers
1    23177
2    24078
Name: count, dtype: int64

In [23]:
print(
    "DTI = 999:",
    (model_base["original_dti"] == 999).sum(),
    f"({(model_base['original_dti'] == 999).mean():.2%})",
)

print(
    "VantageScore = 9999:",
    (model_base["vantage_score_4"] == 9999).sum(),
    f"({(model_base['vantage_score_4'] == 9999).mean():.2%})",
)

print(
    "First-time homebuyer = 9:",
    (model_base["first_time_homebuyer_flag"] == "9").sum(),
)

DTI = 999: 3899 (8.25%)
VantageScore = 9999: 47255 (100.00%)
First-time homebuyer = 9: 1

In [24]:
for col in ["credit_score", "original_dti"]:
    print(f"\n{col}")
    print("-" * 50)

    print("Min:", model_base[col].min())
    print("Max:", model_base[col].max())

    print("\nLowest values:")
    print(model_base[col].value_counts().sort_index().head(15))

    print("\nHighest values:")
    print(model_base[col].value_counts().sort_index().tail(15))

credit_score
--------------------------------------------------
Min: 462
Max: 832

Lowest values:
credit_score
462    1
476    1
479    1
482    1
483    1
485    1
486    1
494    2
497    1
500    1
501    1
505    1
507    1
509    1
512    2
Name: count, dtype: int64

Highest values:
credit_score
816    216
817    134
818     52
819     90
820     81
821     10
822     15
823     63
824      3
825      7
826      3
827      2
829      5
831      1
832      2
Name: count, dtype: int64

original_dti
--------------------------------------------------
Min: 1
Max: 999

Lowest values:
original_dti
1       2
2       6
3       7
4       5
5      19
6      15
7      45
8      45
9      60
10     88
11    111
12    177
13    198
14    279
15    370
Name: count, dtype: int64

Highest values:
original_dti
37     1558
38     1615
39     1694
40     1693
41     1794
42     1773
43     1883
44     2030
45     1806
46      753
47      693
48      775
49      653
50      655
999    3899
Name: count, dtype: int64

In [25]:
collateral_features = [
    "original_ltv",
    "original_cltv",
    "mi_percentage",
    "property_type",
    "occupancy_status",
]

for col in collateral_features:
    print(f"\n{'=' * 60}")
    print(col)
    print("=" * 60)

    print("dtype:", model_base[col].dtype)
    print("missing:", model_base[col].isna().sum())
    print("unique:", model_base[col].nunique(dropna=False))

    print("\nValue counts:")
    print(model_base[col].value_counts(dropna=False).sort_index().to_string())

============================================================
original_ltv
============================================================
dtype: int64
missing: 0
unique: 173

Value counts:
original_ltv
5         1
6         2
7         4
8         4
9         5
10        6
11       10
12       12
13       16
14       21
15       22
16       34
17       42
18       34
19       35
20       41
21       51
22       69
23       61
24       66
25      102
26       76
27       81
28       97
29       99
30      108
31      128
32      126
33      137
34      158
35      167
36      139
37      182
38      169
39      194
40      209
41      179
42      203
43      250
44      210
45      245
46      247
47      287
48      283
49      326
50      423
51      285
52      370
53      368
54      384
55      391
56      445
57      417
58      518
59      465
60      773
61      367
62      471
63      505
64      542
65      653
66      578
67      652
68      695
69      684
70     1136
71      652
72      720
73      844
74      856
75     2840
76      543
77      691
78      803
79      861
80     9849
81       72
82      171
83      266
84      324
85      919
86      187
87      285
88      336
89      352
90     2569
91      126
92      286
93      259
94      290
95     5308
96       36
97      193
98       28
99       28
100      38
101      12
102      28
103      37
104      17
105      25
106      21
107      20
108      15
109       9
110      11
111      16
112      13
113      17
114      11
115      14
116       8
117       6
118      12
119      14
120       5
121       7
122       7
123       8
124      10
125       8
126       8
127       3
128       4
129       4
130       4
131       6
132       6
133       2
135       4
136       3
138       2
139       2
140       4
141       3
142       1
143       3
144       2
145       3
146       5
147       1
148       2
150       1
151       1
152       1
153       1
154       1
155       1
156       2
157       1
159       2
160       2
161       2
162       1
163       1
164       1
165       2
167       1
169       2
170       1
171       2
172       2
173       2
175       1
176       1
181       1
182       1
183       1
197       1
200       1
209       1
241       1
999       1

============================================================
original_cltv
============================================================
dtype: int64
missing: 0
unique: 181

Value counts:
original_cltv
5         1
6         1
7         4
8         4
9         3
10        5
11       10
12       10
13       17
14       19
15       21
16       31
17       37
18       33
19       33
20       38
21       44
22       58
23       56
24       59
25       93
26       73
27       78
28       93
29       93
30      103
31      116
32      122
33      127
34      147
35      151
36      136
37      170
38      162
39      185
40      203
41      176
42      192
43      234
44      200
45      239
46      230
47      264
48      267
49      317
50      392
51      261
52      358
53      339
54      362
55      368
56      423
57      391
58      493
59      438
60      733
61      353
62      453
63      489
64      512
65      612
66      551
67      628
68      671
69      671
70     1117
71      648
72      695
73      813
74      822
75     2760
76      549
77      694
78      775
79      865
80     9618
81       91
82      207
83      295
84      372
85     1001
86      217
87      319
88      380
89      403
90     2992
91      143
92      299
93      271
94      308
95     5420
96       36
97      196
98       35
99       38
100      45
101      20
102      45
103      47
104      28
105      29
106      27
107      20
108      20
109      18
110      17
111      24
112      17
113      22
114      19
115      21
116      14
117      14
118      20
119      12
120      10
121       9
122      10
123      13
124      13
125      10
126      12
127       8
128       6
129       4
130      10
131       5
132       6
133       7
134       2
135       6
136       6
138       6
139       1
140       4
141       5
142       1
143       4
144       1
145       6
146       6
147       3
148       3
149       4
150       3
151       4
152       3
154       1
155       1
156       3
157       1
159       3
160       5
161       1
162       1
163       1
164       2
165       3
169       1
170       1
171       2
172       3
173       1
175       1
176       1
180       1
181       1
182       3
183       1
184       2
190       1
193       1
197       1
200       3
203       1
209       1
219       1
226       1
241       1
854       1
999       1

============================================================
mi_percentage
============================================================
dtype: int64
missing: 0
unique: 16

Value counts:
mi_percentage
0     35761
6       256
12     1570
13        1
15        2
16       83
17       10
18      155
20       42
22        1
25     3589
27        1
30     5722
33        2
35       56
40        4

============================================================
property_type
============================================================
dtype: str
missing: 0
unique: 5

Value counts:
property_type
CO     3750
CP       61
MH      174
PU    12348
SF    30922

============================================================
occupancy_status
============================================================
dtype: str
missing: 0
unique: 3

Value counts:
occupancy_status
I     4011
P    41559
S     1685

In [26]:
model_base[["original_ltv", "original_cltv", "mi_percentage"]].describe()

       original_ltv  original_cltv  mi_percentage
count  47255.000000   47255.000000   47255.000000
mean      73.658322      74.565908       6.119289
std       18.070077      18.580612      11.295345
min        5.000000       5.000000       0.000000
25%       65.000000      66.000000       0.000000
50%       78.000000      79.000000       0.000000
75%       84.000000      85.000000       0.000000
max      999.000000     999.000000      40.000000

In [27]:
print("LTV > 100:")
print(
    (model_base["original_ltv"] > 100).sum(),
    f"({(model_base['original_ltv'] > 100).mean():.2%})",
)

print("\nCLTV > 100:")
print(
    (model_base["original_cltv"] > 100).sum(),
    f"({(model_base['original_cltv'] > 100).mean():.2%})",
)

print("\nCLTV < LTV:")
print(
    (model_base["original_cltv"] < model_base["original_ltv"]).sum(),
)

print("\nCLTV = LTV:")
print(
    (model_base["original_cltv"] == model_base["original_ltv"]).sum(),
)

print("\nCLTV > LTV:")
print(
    (model_base["original_cltv"] > model_base["original_ltv"]).sum(),
)

LTV > 100:
463 (0.98%)

CLTV > 100:
678 (1.43%)

CLTV < LTV:
0

CLTV = LTV:
44457

CLTV > LTV:
2798

In [30]:
mi_by_ltv = pd.crosstab(
    model_base["original_ltv"],
    model_base["mi_percentage"].gt(0),
)

print(mi_by_ltv.loc[70:100])

mi_percentage  False  True
original_ltv
70              1136      0
71               651      1
72               720      0
73               844      0
74               856      0
75              2839      1
76               542      1
77               691      0
78               802      1
79               861      0
80              9846      3
81                47     25
82                38    133
83                53    213
84                50    274
85                48    871
86                44    143
87                42    243
88                28    308
89                43    309
90                55   2514
91                30     96
92                28    258
93                23    236
94                35    255
95                40   5268
96                25     11
97                32    161
98                22      6
99                19      9
100               27     11

In [31]:
loan_features = [
    "original_upb",
    "original_interest_rate",
    "original_loan_term",
    "loan_purpose",
    "channel",
    "amortization_type",
    "prepayment_penalty_flag",
]

for col in loan_features:
    print(f"\n{'=' * 60}")
    print(col)
    print("=" * 60)

    print("dtype:", model_base[col].dtype)
    print("missing:", model_base[col].isna().sum())
    print("unique:", model_base[col].nunique(dropna=False))

    print("\nMost common values:")
    print(model_base[col].value_counts(dropna=False).head(20))

============================================================
original_upb
============================================================
dtype: int64
missing: 0
unique: 655

Most common values:
original_upb
417000    1239
200000     533
100000     520
150000     407
180000     351
120000     341
300000     338
160000     333
140000     291
130000     280
170000     267
250000     267
128000     264
110000     262
190000     256
125000     242
280000     241
176000     238
220000     237
240000     232
Name: count, dtype: int64

============================================================
original_interest_rate
============================================================
dtype: float64
missing: 0
unique: 324

Most common values:
original_interest_rate
4.125    6563
4.250    5161
3.875    4935
3.750    4323
4.000    4231
4.375    2957
3.625    2641
4.500    1964
4.625    1845
3.500    1771
3.250    1362
4.750    1342
3.375    1274
3.125    1225
3.000    1018
3.990    1007
4.875     684
2.875     652
5.000     191
3.950     182
Name: count, dtype: int64

============================================================
original_loan_term
============================================================
dtype: int64
missing: 0
unique: 77

Most common values:
original_loan_term
360    34313
180     9286
240     2471
120      524
300      338
276       33
288       29
168       26
348       21
324       19
144       18
264       17
156       16
336       15
252       13
132        9
312        8
228        8
216        7
204        4
Name: count, dtype: int64

============================================================
loan_purpose
============================================================
dtype: str
missing: 0
unique: 3

Most common values:
loan_purpose
P    20878
N    16554
C     9823
Name: count, dtype: int64

============================================================
channel
============================================================
dtype: str
missing: 0
unique: 3

Most common values:
channel
R    29115
C    13225
B     4915
Name: count, dtype: int64

============================================================
amortization_type
============================================================
dtype: str
missing: 0
unique: 1

Most common values:
amortization_type
FRM    47255
Name: count, dtype: int64

============================================================
prepayment_penalty_flag
============================================================
dtype: str
missing: 0
unique: 1

Most common values:
prepayment_penalty_flag
N    47255
Name: count, dtype: int64

In [32]:
model_base[
    [
        "original_upb",
        "original_interest_rate",
        "original_loan_term",
    ]
].describe()

        original_upb  original_interest_rate  original_loan_term
count   47255.000000            47255.000000        47255.000000
mean   221901.089832                3.974441          314.566586
std    118704.199071                0.455129           76.330162
min     10000.000000                2.375000           96.000000
25%    130000.000000                3.750000          240.000000
50%    199000.000000                4.000000          360.000000
75%    296000.000000                4.250000          360.000000
max    974000.000000                5.500000          366.000000

In [33]:
admin_features = [
    "property_state",
    "postal_code",
    "msa",
    "seller_name",
    "super_conforming_flag",
    "special_eligibility_program",
    "harp_indicator",
    "pre_harp_loan_id",
    "property_valuation_method",
    "interest_only_indicator",
    "first_payment_date",
    "maturity_date",
]

for col in admin_features:
    print(f"\n{'=' * 60}")
    print(col)
    print("=" * 60)

    print("dtype:", model_base[col].dtype)
    print("missing:", model_base[col].isna().sum())
    print("missing %:", f"{model_base[col].isna().mean():.2%}")
    print("unique:", model_base[col].nunique(dropna=False))

    print("\nMost common values:")
    print(model_base[col].value_counts(dropna=False).head(15))

============================================================
property_state
============================================================
dtype: str
missing: 0
missing %: 0.00%
unique: 54

Most common values:
property_state
CA    7297
TX    3236
FL    2807
IL    2182
MI    1692
CO    1613
WA    1502
OH    1495
NC    1460
NY    1460
GA    1401
PA    1369
AZ    1280
VA    1256
MN    1186
Name: count, dtype: int64

============================================================
postal_code
============================================================
dtype: string
missing: 0
missing %: 0.00%
unique: 866

Most common values:
postal_code
945    623
750    617
300    457
852    406
606    390
980    385
840    383
600    378
917    370
926    367
601    355
802    346
913    338
956    320
928    312
Name: count, dtype: int64[pyarrow]

============================================================
msa
============================================================
dtype: string
missing: 5433
missing %: 11.50%
unique: 446

Most common values:
msa
<NA>     5433
31084    1532
19740     962
38060     945
12060     933
19124     905
26420     901
16984     865
47894     834
33460     815
40140     790
35614     718
42644     716
11244     716
38900     701
Name: count, dtype: int64[pyarrow]

============================================================
seller_name
============================================================
dtype: str
missing: 0
missing %: 0.00%
unique: 25

Most common values:
seller_name
OTHER                                                        18454
WELLS FARGO BANK, N.A.                                        6498
U.S. BANK N.A.                                                3023
BANK OF AMERICA, N.A.                                         2507
QUICKEN LOANS INC.                                            2492
BRANCH BANKING & TRUST COMPANY                                1735
CALIBER HOME LOANS, INC.                                      1274
STEARNS LENDING, LLC                                          1172
LOANDEPOT.COM, LLC                                            1156
FRANKLIN AMERICAN MORTGAGE COMPANY                            1031
CITIMORTGAGE, INC.                                             999
JPMORGAN CHASE BANK, N.A.                                      954
NATIONSTAR MORTGAGE LLC                                        882
FLAGSTAR BANK, FSB                                             870
UNITED SHORE FINANCIAL SERVICES, LLC., DBA SHORE MORTGAGE      729
Name: count, dtype: int64

============================================================
super_conforming_flag
============================================================
dtype: str
missing: 0
missing %: 0.00%
unique: 2

Most common values:
super_conforming_flag
N    45458
Y     1797
Name: count, dtype: int64

============================================================
special_eligibility_program
============================================================
dtype: str
missing: 46942
missing %: 99.34%
unique: 3

Most common values:
special_eligibility_program
NaN    46942
H        306
F          7
Name: count, dtype: int64

============================================================
harp_indicator
============================================================
dtype: str
missing: 0
missing %: 0.00%
unique: 2

Most common values:
harp_indicator
N    43359
Y     3896
Name: count, dtype: int64

============================================================
pre_harp_loan_id
============================================================
dtype: string
missing: 43359
missing %: 91.76%
unique: 3897

Most common values:
pre_harp_loan_id
<NA>            43359
A07Q20031002        1
F03Q30664737        1
F07Q20144625        1
F04Q30321412        1
F09Q20218625        1
F08Q30174218        1
F01Q20435738        1
F03Q40540427        1
F09Q10032588        1
F06Q10317281        1
F04Q30361570        1
F09Q10018299        1
F08Q10294928        1
F06Q10183815        1
Name: count, dtype: int64[pyarrow]

============================================================
property_valuation_method
============================================================
dtype: int64
missing: 0
missing %: 0.00%
unique: 1

Most common values:
property_valuation_method
7    47255
Name: count, dtype: int64

============================================================
interest_only_indicator
============================================================
dtype: str
missing: 0
missing %: 0.00%
unique: 1

Most common values:
interest_only_indicator
N    47255
Name: count, dtype: int64

============================================================
first_payment_date
============================================================
dtype: string
missing: 0
missing %: 0.00%
unique: 27

Most common values:
first_payment_date
201505    5003
201512    4262
201506    4144
201509    3961
201602    3951
201507    3922
201510    3902
201511    3896
201504    3833
201508    3781
201601    3517
201503    2863
201603     123
201502      37
201609      12
Name: count, dtype: int64[pyarrow]

============================================================
maturity_date
============================================================
dtype: string
missing: 0
missing %: 0.00%
unique: 214

Most common values:
maturity_date
204504    3462
204511    3156
204505    2989
204601    2984
204506    2879
204508    2875
204509    2857
204510    2844
204507    2768
204503    2726
204512    2603
204502    2037
203004    1061
203008     827
203005     813
Name: count, dtype: int64[pyarrow]

In [34]:
eda = model_base.copy()

eda["dti_missing"] = eda["original_dti"].eq(999)

dti_missing_summary = eda.groupby("dti_missing")["ever_90dpd_24m"].agg(
    loans="size",
    events="sum",
    event_rate="mean",
)

dti_missing_summary["event_rate_pct"] = (dti_missing_summary["event_rate"] * 100).round(
    3
)

display(dti_missing_summary)

             loans  events  event_rate  event_rate_pct
dti_missing
False        43356     275    0.006343           0.634
True          3899      68    0.017440           1.744

In [35]:
model_base["original_dti"].median()

np.float64(36.0)

In [36]:
from credit_risk.features.origination import (
    select_baseline_features,
    normalize_sentinel_values,
    add_missing_indicators,
)

X = select_baseline_features(model_base)
X = normalize_sentinel_values(X)
X = add_missing_indicators(X)

missing_summary = (
    X.isna()
    .sum()
    .to_frame("missing")
    .assign(missing_pct=lambda x: (x["missing"] / len(X) * 100).round(2))
    .query("missing > 0")
    .sort_values("missing_pct", ascending=False)
)

display(missing_summary)

                           missing  missing_pct
original_dti                  3899         8.25
first_time_homebuyer_flag        1         0.00
original_ltv                     1         0.00
original_cltv                    1         0.00

In [37]:
dates = pd.to_datetime(
    model_base["first_payment_date"],
    format="%Y%m",
)

print("Earliest:", dates.min())
print("Latest:", dates.max())

display(dates.dt.to_period("M").value_counts().sort_index())

Earliest: 2015-02-01 00:00:00
Latest: 2017-05-01 00:00:00

first_payment_date
2015-02      37
2015-03    2863
2015-04    3833
2015-05    5003
2015-06    4144
2015-07    3922
2015-08    3781
2015-09    3961
2015-10    3902
2015-11    3896
2015-12    4262
2016-01    3517
2016-02    3951
2016-03     123
2016-04      10
2016-05       4
2016-06       5
2016-07       4
2016-08       5
2016-09      12
2016-10       6
2016-11       4
2016-12       4
2017-01       2
2017-02       2
2017-04       1
2017-05       1
Freq: M, Name: count, dtype: int64

In [38]:
tmp = model_base.assign(first_payment_month=dates.dt.to_period("M"))

monthly_target = tmp.groupby("first_payment_month")["ever_90dpd_24m"].agg(
    loans="size",
    events="sum",
    event_rate="mean",
)

monthly_target["event_rate_pct"] = (monthly_target["event_rate"] * 100).round(3)

display(monthly_target)

                     loans  events  event_rate  event_rate_pct
first_payment_month
2015-02                 37       0    0.000000           0.000
2015-03               2863      19    0.006636           0.664
2015-04               3833      24    0.006261           0.626
2015-05               5003      24    0.004797           0.480
2015-06               4144      24    0.005792           0.579
2015-07               3922      21    0.005354           0.535
2015-08               3781      27    0.007141           0.714
2015-09               3961      33    0.008331           0.833
2015-10               3902      29    0.007432           0.743
2015-11               3896      20    0.005133           0.513
2015-12               4262      28    0.006570           0.657
2016-01               3517      42    0.011942           1.194
2016-02               3951      50    0.012655           1.266
2016-03                123       2    0.016260           1.626
2016-04                 10       0    0.000000           0.000
2016-05                  4       0    0.000000           0.000
2016-06                  5       0    0.000000           0.000
2016-07                  4       0    0.000000           0.000
2016-08                  5       0    0.000000           0.000
2016-09                 12       0    0.000000           0.000
2016-10                  6       0    0.000000           0.000
2016-11                  4       0    0.000000           0.000
2016-12                  4       0    0.000000           0.000
2017-01                  2       0    0.000000           0.000
2017-02                  2       0    0.000000           0.000
2017-04                  1       0    0.000000           0.000
2017-05                  1       0    0.000000           0.000